# PREENTREGA NÚMERO 01
#### Comisión 61600
#### Data Science I - Fundamentos para la Ciencia de Datos

#### Alumno: Michael Meneses Mora
#### Dataset: Estadísticas del universo Pokémon

## ABSTRACT

### Resumen:
##### El análisis realizado se centra en entender más en profundidad como se componen las estadísticas de cada Pokémon. Comprender su naturaleza, sus atríbutos y como se comporta respecto a sus pares. Los atributos considerados serán "Tipo principal", "Tipo secundario", "Ataque", "Velocidad", "Defensa", entre otros.

### Hipótesis planteada:
##### A partir del dataset en análisis queremos entender los atributos de cada integrante
+ Visualizar sus estadísticas
+ Identificar al más poderoso
+ Conocer los tipos principales y secundario

#### Preguntas a responder...
+ ¿Cómo se distribuyen los Pokémon por tipo?
+ ¿Cómo están distribuidas las generaciones por cantidad de integrantes?
+ ¿Cúal es el tipo que está más presente en cada generación?
+ ¿Existen outlier dentro de cada generación?

In [1]:
# Comienzo importando las librerias necesarias y apago los warnings
import pandas as pd
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [14]:
# Cargo la base para el análisis, defino indice por la columna "#" y limpio la columna "Name"
df = pd.read_csv('_pokemon.csv')
df = df.set_index('#')
df['Name'] = df['Name'].str.replace(".*(?=Mega)", "")
df

,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
#,,,,,,,,,,,,
1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,Mega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
719,Mega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True